PROPERTY_FRAME_WIDTH = 300
PROPERTY_FRAME_HEIGHT = 870
PROPERTY_WINDOW_ANIMATION_START_X = -350
PROPERTY_WINDOW_ANIMATION_START_y = 120
PROPERTY_WINDOW_ANIMATION_END_X = 20
PROPERTY_WINDOW_ANIMATION_END_y = 120
PROPERTY_ANIMATION_DURATION = 250